group: travis_lts
language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-27.0.3
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - android-27
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build connectedCheck createDebugCoverageReport jacocoTestReport assemble -s -PversionBuildNumber=${TRAVIS_BUILD_NUMBER}

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file: "*/build/outputs/apk/*.apk"
  file_glob: true
  overwrite: true
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^release.*$"
    
notifications:
  email:
    recipients:
      - mivola@gmx.de
    on_success: change
    on_failure: change
